"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Optional

@dataclass
class Package:
    name: str
    version: str
    download_size: int
    install_size: int
    repo: str
    last_update: int
    depends: Optional[list[str]] = ...
    make_depends: Optional[list[str]] = ...
    wanted: Optional[bool] = ...
    def __eq__(self, other: Any) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    


